/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as HostRouteImport } from './routes/host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiGenerateQuestionsRouteImport } from './routes/api/ai/generate-questions'

const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateQuestionsRoute = ApiAiGenerateQuestionsRouteImport.update({
  id: '/api/ai/generate-questions',
  path: '/api/ai/generate-questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/presentation': typeof PresentationRoute
  '/api/ai/generate-questions': typeof ApiAiGenerateQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/presentation': typeof PresentationRoute
  '/api/ai/generate-questions': typeof ApiAiGenerateQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/presentation': typeof PresentationRoute
  '/api/ai/generate-questions': typeof ApiAiGenerateQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/host' | '/presentation' | '/api/ai/generate-questions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/host' | '/presentation' | '/api/ai/generate-questions'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/presentation'
    | '/api/ai/generate-questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRoute
  PresentationRoute: typeof PresentationRoute
  ApiAiGenerateQuestionsRoute: typeof ApiAiGenerateQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-questions': {
      id: '/api/ai/generate-questions'
      path: '/api/ai/generate-questions'
      fullPath: '/api/ai/generate-questions'
      preLoaderRoute: typeof ApiAiGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRoute,
  PresentationRoute: PresentationRoute,
  ApiAiGenerateQuestionsRoute: ApiAiGenerateQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
